//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/surf_swift.html
gfx/env/alien1bk.tga
gfx/env/alien1dn.tga
gfx/env/alien1ft.tga
gfx/env/alien1lf.tga
gfx/env/alien1rt.tga
gfx/env/alien1up.tga
maps/surf_swift.bsp
